const SITE = "__SITE_URL__";
const icons = {
 building:`<svg viewBox="0 0 24 24"><path d="M4 21V5a2 2 0 0 1 2-2h11v18M2 21h20M8 7h2m3 0h1M8 11h2m3 0h1M8 15h2m3 0h1M8 21v-2h5v2"/></svg>`,
 phone:`<svg viewBox="0 0 24 24"><path d="M22 17v3a2 2 0 0 1-2.2 2A19.8 19.8 0 0 1 2 4.2 2 2 0 0 1 4 2h3a2 2 0 0 1 2 1.7c.1 1 .4 1.9.7 2.8a2 2 0 0 1-.5 2.1L8 9.9a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5c.9.3 1.9.6 2.8.7A2 2 0 0 1 22 17z"/></svg>`,
 mail:`<svg viewBox="0 0 24 24"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 7-8.8 5.6a2.2 2.2 0 0 1-2.4 0L2 7"/></svg>`,
 globe:`<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15 15 0 0 1 0 20M12 2a15 15 0 0 0 0 20"/></svg>`,
 linkedin:`<svg viewBox="0 0 24 24"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-4 0v7h-4V9h4v2a5 5 0 0 1 2-3zM2 9h4v12H2z"/><circle cx="4" cy="4" r="2"/></svg>`,
 download:`<svg viewBox="0 0 24 24"><path d="M12 3v12m-5-5 5 5 5-5M5 21h14a2 2 0 0 0 2-2v-3M3 16v3a2 2 0 0 0 2 2"/></svg>`
};
const row=(href,icon,label,value,external=false)=>`<a class="row" href="${href}"${external?' target="_blank" rel="noreferrer"':''}><span class="icon">${icons[icon]}</span><span class="copy"><small>${label}</small><strong>${value}</strong></span><span class="chev">›</span></a>`;
const page=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#005596"><title>Sean Healey | Macomb County Digital Business Card</title><meta name="description" content="Contact Sean Healey, Senior Communications Specialist with Macomb County Planning and Economic Development."><style>
:root{font-family:Arial,Helvetica,sans-serif;color:#17324a;background:#eaf2f8;--blue:#0066a6}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 50% -10%,#fff 0,#eef5fa 35%,#dbe9f3 100%);padding:18px 14px 32px}main{width:min(100%,520px);margin:auto;background:#fff;border-radius:22px;overflow:hidden;box-shadow:0 18px 60px rgba(18,60,91,.18);border:1px solid #d2e2ed}.brand{padding:22px;background:linear-gradient(135deg,#0068a7,#004d7d);color:#fff;position:relative}.department{font-size:18px;line-height:1.08;font-weight:700}.county{margin-top:5px;font-size:10px;letter-spacing:.2em;font-weight:700}.identity{text-align:center;padding:27px 22px 18px}.proof{font-size:10px;text-transform:uppercase;letter-spacing:.14em;color:#4f7691;font-weight:700;margin:0 0 14px}.identity h1{font-size:36px;letter-spacing:-.035em;margin:0;color:#143b58}.title{font-size:15px;line-height:1.45;margin:8px 0 3px;color:#315a75}.org{font-size:14px;line-height:1.4;margin:0 auto;max-width:360px;font-weight:700;color:#005c96}.primary{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:0 18px 16px}.button{min-height:48px;border-radius:11px;display:flex;align-items:center;justify-content:center;gap:8px;text-decoration:none;font-size:14px;font-weight:700}.save{background:var(--blue);color:#fff}.email{border:1.5px solid var(--blue);color:var(--blue);background:#fff}.button svg,.icon svg{fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.button svg{width:19px;height:19px}.rows{padding:0 18px}.row{display:grid;grid-template-columns:42px minmax(0,1fr) 18px;align-items:center;min-height:69px;border-top:1px solid #e3edf3;text-decoration:none;color:inherit}.icon{display:grid;place-items:center;width:35px;height:35px;border-radius:9px;background:#e7f3fa;color:var(--blue)}.icon svg{width:21px;height:21px}.copy{min-width:0}.copy small{display:block;color:#5f7a8c;font-size:11px;margin-bottom:3px}.copy strong{display:block;color:#183e58;font-size:14px;line-height:1.25;overflow-wrap:anywhere}.chev{font-size:25px;color:#5b8cac}.share{margin:18px;background:#edf6fb;border-radius:14px;padding:15px;display:flex;align-items:center;gap:15px}.share img{width:92px;height:92px;border-radius:8px;background:#fff;padding:5px}.share strong{display:block;font-size:14px;color:#174765}.share p{font-size:12px;color:#567386;line-height:1.4;margin:5px 0 0}footer{background:#f6f9fb;border-top:1px solid #dfebf2;padding:15px 20px;text-align:center;color:#577486;font-size:11px;line-height:1.5}@media(max-width:390px){body{padding:0;background:#fff}main{border:0;border-radius:0;box-shadow:none;min-height:100vh}.identity h1{font-size:33px}.primary,.rows{padding-left:14px;padding-right:14px}.share{margin:14px}.copy strong{font-size:13px}}
</style></head><body><main><header class="brand"><div class="department">Planning and<br>Economic Development</div><div class="county">MACOMB COUNTY, MI</div></header><section class="identity"><p class="proof">Digital Business Card</p><h1>Sean Healey</h1><p class="title">Senior Communications Specialist</p><p class="org">Macomb County Planning and Economic Development</p></section><div class="primary"><a class="button save" href="/sean-healey.vcf" download>${icons.download} Save Contact</a><a class="button email" href="mailto:sean.healey@macombgov.org">${icons.mail} Email Sean</a></div><section class="rows" aria-label="Contact information">${row('tel:+15864935740','building','Office','586-493-5740')}${row('tel:+15862068483','phone','Cell','586-206-8483')}${row('mailto:sean.healey@macombgov.org','mail','Email','sean.healey@macombgov.org')}${row('https://www.macombgov.org/departments/planning-economic-development','globe','Planning and Economic Development','macombgov.org/ped',true)}${row('https://www.linkedin.com/search/results/all/?keywords=Sean%20Healey%20Macomb%20County','linkedin','LinkedIn','Professional profile',true)}${row('https://maps.apple.com/?q=1+South+Main+Street+Mount+Clemens+MI+48043','building','Office','1 South Main St. · 7th floor · Mount Clemens, MI 48043',true)}</section><section class="share"><img src="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(SITE)}" alt="QR code to open this digital business card"><div><strong>Scan to open this card</strong><p>Save it to your phone’s home screen or share the link by QR code or NFC.</p></div></section><footer>Macomb County Planning and Economic Development<br>Proof-of-concept digital business card</footer></main></body></html>`;
const vcard=`BEGIN:VCARD\r\nVERSION:3.0\r\nN:Seibert;Todd;;;\r\nFN:Todd Seibert\r\nORG:Macomb County Planning and Economic Development\r\nTITLE:Economic Development Project Manager\r\nTEL;TYPE=WORK,VOICE:586-469-6298\r\nTEL;TYPE=CELL,VOICE:586-719-0349\r\nEMAIL;TYPE=INTERNET,WORK:todd.seibert@macombgov.org\r\nADR;TYPE=WORK:;;1 South Main Street, 7th Floor;Mount Clemens;MI;48043;USA\r\nURL:https://www.macombgov.org/departments/planning-economic-development\r\nURL;TYPE=LinkedIn:https://www.linkedin.com/in/todd-seibert-b2576511a/\r\nNOTE:Digital business card: ${SITE}\r\nEND:VCARD\r\n`;
const pageWithLogo=page.replace('</style>','.brand{padding:18px 22px;display:flex;align-items:center;justify-content:space-between;gap:18px}.brand-copy{min-width:0}.brand-logo{width:82px;height:82px;object-fit:contain;flex:0 0 auto}</style>').replace('<header class="brand"><div class="department">Planning and<br>Economic Development</div><div class="county">MACOMB COUNTY, MI</div></header>','<header class="brand"><div class="brand-copy"><div class="department">Planning and<br>Economic Development</div><div class="county">MACOMB COUNTY, MI</div></div><img class="brand-logo" src="https://www.macombgov.org/themes/custom/if_design_system/images/macomb-logo-white-2023.svg" alt="Macomb County logo"></header>');
const pageForTodd=pageWithLogo
 .replaceAll('Sean Healey','Todd Seibert')
 .replaceAll('Senior Communications Specialist','Economic Development Project Manager')
 .replaceAll('sean.healey@macombgov.org','todd.seibert@macombgov.org')
 .replaceAll('Email Sean','Email Todd')
 .replaceAll('/sean-healey.vcf','/todd-seibert.vcf')
 .replaceAll('tel:+15864935740','tel:+15864696298')
 .replaceAll('586-493-5740','586-469-6298')
 .replaceAll('tel:+15862068483','tel:+15867190349')
 .replaceAll('586-206-8483','586-719-0349')
 .replace('https://www.linkedin.com/search/results/all/?keywords=Sean%20Healey%20Macomb%20County','https://www.linkedin.com/in/todd-seibert-b2576511a/');
export default{async fetch(request){const url=new URL(request.url);const siteUrl=url.origin;const livePage=pageForTodd.replaceAll(encodeURIComponent(SITE),encodeURIComponent(siteUrl)).replaceAll(SITE,siteUrl);const liveVcard=vcard.replaceAll(SITE,siteUrl);if(url.pathname==="/")return new Response(livePage,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"public, max-age=300"}});if(url.pathname==="/todd-seibert.vcf")return new Response(liveVcard,{headers:{"content-type":"text/vcard; charset=utf-8","content-disposition":"attachment; filename=Todd-Seibert-Macomb-County.vcf"}});return new Response("Not found",{status:404})}};
